config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present? && request.subdomain != "www"
  end
end
class SubdomainBlank
  def self.matches?(request)
    request.subdomain().blank?  || request.subdomain == "www"
  end
end


Rails.application.routes.draw do
	
	constraints(SubdomainPresent) do
    root 'static_pages#home'
    devise_for :users
    resources :users, only: :index
  end
  
  constraints(SubdomainBlank) do
    root 'static_pages#home'
    resources :accounts, only: [:new, :create]
    get '/contact', to: 'static_pages#contact'
	  get '/help', to: 'static_pages#help'
	  get '/about', to: 'static_pages#about'
	  get '/signup', to: 'users#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	RESTRICTED_SUBDOMAINS = %w(www)

  belongs_to :owner, class_name: 'User'

  validates :owner, presence: true
  validates :subdomain, presence: true,
                        uniqueness: { case_sensitive: false },
                        format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters' },
                        exclusion: { in: RESTRICTED_SUBDOMAINS, message: 'restricted' }

  before_validation :downcase_subdomain

  accepts_nested_attributes_for :owner

private
  def downcase_subdomain
    self.subdomain = subdomain.try(:downcase)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organisation.rb
class Organisation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	skip_before_action :authenticate_user!, only: [:new, :create]
	
	def new
		@account = Account.new
		@account.build_owner
	end

	def create
    	@account = Account.new(account_params)
    	if @account.valid?
      Apartment::Tenant.create(@account.subdomain)
      Apartment::Tenant.switch!(@account.subdomain)
      @account.save
      redirect_to new_user_session_url(subdomain: @account.subdomain)
    else
      render action: 'new'
    end
  end

	private 
		def account_params
			params.require(:account).permit(:subdomain, owner_attributes: [:first_name, :last_name, :email, :password, :password_confirmation])
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :load_schema, :authenticate_user!

  protected

 def load_schema
    Apartment::Tenant.switch!('public')
    return unless request.subdomain.present?

    account = Account.find_by(subdomain: request.subdomain)
    if account 
      Apartment::Tenant.switch!(request.subdomain)
    else
      redirect_to root_url(subdomain: false)
    end
  end

  def after_sign_out_path_for(resource_or_scope)
  	new_user_session_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :contact, :help, :about]

  def home
  end

  def contact
  end

  def help
  end

  def about
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(title = "")
		base_title = "Student success platform"
		if title.empty?
			base_title
		else 
			"#{title} | #{base_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <h2>Create an Account</h2>

    <%= simple_form_for @account do |f| %>
      <%= f.fields_for :owner do |o| %>
        <%= o.input :first_name %>
        <%= o.input :last_name %>
        <%= o.input :email %>
        <%= o.input :password %>
        <%= o.input :password_confirmation %>
      <% end %>

      <%= f.input :subdomain do %>
        <div class="input-group">
          <%= f.input_field :subdomain, class: 'form-control' %>
          <span class="input-group-addon">.timetracker.dev</span>
        </div>
      <% end %>
      <%= f.button :submit, class: 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
	<small>
		The first student success platform 
		by Workshopr
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Help", help_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<%= link_to "Studinsight", root_path, class: "navbar-brand" %>
		</div>
		<ul class="nav navbar-nav navbar-right">
		<% if user_signed_in? %>
        	<li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'btn btn-default navbar-btn' %></li>	
	    <% end %>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Help", help_path %></li>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "layouts/header" %>
    <%= render "layouts/flash_messages" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

<%= link_to "Signup", new_account_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>